### ISSUE TITLE
Example config file

### ISSUE THREAD

**Issue by liki-mc** [SarahRoseLives/ModTrack#2]
Hello,

It seems like we have a similar use case for the OpenTTD Admin port. Would it be possible to add an example config file to the repo?

**Comment by SarahRoseLives** [comment]
I plan to, just noticed that you heavily updated things. I need to take a look at that as I'm not familiar with cogs at all.

It'll likely do much better than my UDP socket solutions though :p

This is the config I use but I'll clean it up and add it once I figure out cogs so I can get this running.

[ModRail]


[Discord]
token = 
channel_id = 
bot_id_on_discord = 
discord_admin_role_id = 

channel_admin_request = 
channel_chat_messsages = 
channel_bot_commands = 
channel_log_messages = 

that's my current config with the IDs removed.
